export const LIMITS = {
  OTP_LENGTH: 6,
  OTP_TTL_SECONDS: 5 * 60,
  OTP_MAX_ATTEMPTS: 5,
  OTP_RESEND_COOLDOWN_SECONDS: 30,
  OTP_MAX_PER_HOUR: 5,
  INVITE_TTL_DAYS: 7,
  MAX_ROOM_MEMBERS: 50,
  MAX_SYNC_BATCH: 200,
  MAX_EVENTS_BATCH: 100,
  MAX_NOTE_LENGTH: 500,
  /** 1 crore in major units; stored as minor units. */
  MAX_AMOUNT_MINOR: 10_000_000_00,
  PAGE_SIZE: 30,
  BUDGET_ALERT_THRESHOLDS: [80, 100],
  ACTIVITY_LOG_TTL_DAYS: 365,
  APP_EVENT_TTL_DAYS: 90,
} as const;
