/** Machine-readable error codes so clients can react without parsing messages. */
export const ERROR_CODES = {
  VALIDATION: 'VALIDATION',
  UNAUTHORIZED: 'UNAUTHORIZED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  SESSION_REVOKED: 'SESSION_REVOKED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  ACCOUNT_BLOCKED: 'ACCOUNT_BLOCKED',
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_TOO_MANY_ATTEMPTS: 'OTP_TOO_MANY_ATTEMPTS',
  IDENTITY_IN_USE: 'IDENTITY_IN_USE',
  UNSETTLED_BALANCE: 'UNSETTLED_BALANCE',
  OWNER_MUST_TRANSFER: 'OWNER_MUST_TRANSFER',
  ROOM_ARCHIVED: 'ROOM_ARCHIVED',
  CURRENCY_LOCKED: 'CURRENCY_LOCKED',
  TRANSACTION_LOCKED: 'TRANSACTION_LOCKED',
  INVITE_INVALID: 'INVITE_INVALID',
  SPLIT_INVALID: 'SPLIT_INVALID',
  UPGRADE_REQUIRED: 'UPGRADE_REQUIRED',
  MAINTENANCE: 'MAINTENANCE',
  INTERNAL: 'INTERNAL',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
