/** TanStack Query keys shared by mobile and admin so invalidation stays consistent. */
export const qk = {
  appSettings: ['app-settings'] as const,
  me: ['me'] as const,
  sessions: ['me', 'sessions'] as const,
  categories: ['categories'] as const,
  transactions: (filters?: object) => ['transactions', filters ?? {}] as const,
  transaction: (id: string) => ['transactions', 'detail', id] as const,
  budgets: ['budgets'] as const,
  recurring: ['recurring'] as const,
  insights: (filters: object) => ['insights', filters] as const,
  rooms: ['rooms'] as const,
  room: (id: string) => ['rooms', id] as const,
  roomSpendingAll: ['rooms', 'spending'] as const,
  roomSpending: (from: string, to: string) => ['rooms', 'spending', from, to] as const,
  roomSpendingItems: (from: string, to: string) => ['rooms', 'spending', 'items', from, to] as const,
  roomMembers: (id: string) => ['rooms', id, 'members'] as const,
  roomInvites: (id: string) => ['rooms', id, 'invites'] as const,
  roomExpenses: (id: string) => ['rooms', id, 'expenses'] as const,
  roomExpense: (id: string, expenseId: string) => ['rooms', id, 'expense', expenseId] as const,
  roomBalances: (id: string) => ['rooms', id, 'balances'] as const,
  roomBudget: (id: string) => ['rooms', id, 'budget'] as const,
  roomSettlements: (id: string) => ['rooms', id, 'settlements'] as const,
  myInvites: ['invites'] as const,
  notifications: ['notifications'] as const,
  admin: {
    me: ['admin', 'me'] as const,
    dashboard: (days: number) => ['admin', 'dashboard', days] as const,
    users: (q: object) => ['admin', 'users', q] as const,
    user: (id: string) => ['admin', 'users', 'detail', id] as const,
    userActivity: (id: string, page: number) => ['admin', 'users', id, 'activity', page] as const,
    userTransactions: (id: string, page: number) => ['admin', 'users', id, 'transactions', page] as const,
    rooms: (q: object) => ['admin', 'rooms', q] as const,
    room: (id: string) => ['admin', 'rooms', 'detail', id] as const,
    activity: (q: object) => ['admin', 'activity', q] as const,
    events: (q: object) => ['admin', 'events', q] as const,
    categories: ['admin', 'categories'] as const,
    admins: ['admin', 'admins'] as const,
  },
};
